\c prod;

CREATE TABLE IF NOT EXISTS job (
    id SERIAL PRIMARY KEY,
    job_name VARCHAR(256) NOT NULL UNIQUE,
    flow_id INTEGER REFERENCES flow (id) NOT NULL,
    status VARCHAR(1) DEFAULT 'N' NOT NULL,
    created_dt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    start_dt TIMESTAMP WITHOUT TIME ZONE,
    updated_dt TIMESTAMP WITHOUT TIME ZONE
);
